Arm64 support (#3)
- switch WORKDIR to /
Somehow needed, otherwise we end up with:
Error: Unable to initialize main class io.finn.signald.Main
Caused by: java.lang.ExceptionInInitializerError: null
When running signald
- Added container tests
- Added host tests